"""Strict, host-owned validation packets.

The packet is deliberately implemented with the standard library.  It is a
small schema boundary (a typed record with validation), not another language
model and not a second grader.  The host builds it from an execution result;
the actor and worker cannot choose its status or paths.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path


SCHEMA_VERSION = "1"
MAX_COMMAND = 240
MAX_CWD = 160
MAX_PATHS = 12
MAX_PATH = 240
MAX_TEST_ID = 240
MAX_DIAGNOSTIC = 900
MAX_EVIDENCE = 1200
VALID_STATUSES = frozenset({"setup_failure", "behavior_failure", "unknown_failure"})


class ValidationPacketError(ValueError):
    """Raised when a packet would cross the host/agent boundary malformed."""


@dataclass(frozen=True)
class PrimaryFailure:
    """The first actionable failure found in one validation result."""

    kind: str
    error_type: str = ""
    message: str = ""
    path: str = ""
    line: int | None = None
    function: str = ""
    test_id: str = ""

    def __post_init__(self) -> None:
        for value, limit in (
            (self.kind, 40), (self.error_type, 80), (self.message, 500),
            (self.path, MAX_PATH), (self.function, 120), (self.test_id, MAX_TEST_ID),
        ):
            if not isinstance(value, str) or len(value) > limit:
                raise ValidationPacketError("primary failure field exceeds packet limit")
        if self.line is not None and (not isinstance(self.line, int) or self.line < 1):
            raise ValidationPacketError("invalid primary failure line")


@dataclass(frozen=True)
class FailedValidationPacket:
    """Bounded factual evidence generated by the host."""

    schema_version: str
    validation_status: str
    tool_name: str
    executed_command: str
    cwd: str
    exit_code: int | None
    primary_failure: PrimaryFailure | None
    detected_test_path: str
    detected_source_path: str
    transaction_overlaps: tuple[str, ...]
    source_paths: tuple[str, ...]
    test_paths: tuple[str, ...]
    deterministic_evidence: str
    evidence_sha256: str

    def __post_init__(self) -> None:
        if self.schema_version != SCHEMA_VERSION:
            raise ValidationPacketError("unsupported validation packet schema")
        if self.validation_status not in VALID_STATUSES:
            raise ValidationPacketError("invalid validation status")
        if not isinstance(self.tool_name, str) or not self.tool_name:
            raise ValidationPacketError("tool_name is required")
        if len(self.executed_command) > MAX_COMMAND or len(self.cwd) > MAX_CWD:
            raise ValidationPacketError("command or cwd exceeds packet limit")
        for values in (self.transaction_overlaps, self.source_paths, self.test_paths):
            if len(values) > MAX_PATHS or any(len(path) > MAX_PATH for path in values):
                raise ValidationPacketError("packet contains too many or too-long paths")
            if any(Path(path).is_absolute() or ".." in Path(path).parts for path in values):
                raise ValidationPacketError("packet contains an unsafe path")
        if len(self.detected_test_path) > MAX_PATH or len(self.detected_source_path) > MAX_PATH:
            raise ValidationPacketError("detected path exceeds packet limit")
        if len(self.deterministic_evidence) > MAX_EVIDENCE:
            raise ValidationPacketError("evidence exceeds packet limit")
        if len(self.evidence_sha256) != 64:
            raise ValidationPacketError("invalid evidence digest")

    def as_dict(self) -> dict:
        data = asdict(self)
        data["transaction_overlaps"] = list(self.transaction_overlaps)
        data["source_paths"] = list(self.source_paths)
        data["test_paths"] = list(self.test_paths)
        return data

    def to_json(self) -> str:
        """Serialize canonical JSON for an actor repair packet."""
        return json.dumps(self.as_dict(), sort_keys=True, separators=(",", ":"))


_TRACE_LOCATION = re.compile(
    r'File\s+["\'](?P<path>[^"\']+)["\'],\s+line\s+(?P<line>\d+)'
)
_COMPACT_LOCATION = re.compile(
    r'(?P<path>(?:[^\s():]+/)*[^\s():]+\.(?:py|js|jsx|ts|tsx|java|go|rb|rs|php|c|cpp|h)):(?P<line>\d+)(?::\d+)?'
)
_TEST_FAILURE = re.compile(
    r'\b(?:FAILED|ERROR)\s+(?P<test>[^\s]+::[^\s]+)(?:\s+-\s+(?P<message>.*))?',
    re.IGNORECASE,
)
_EXCEPTION = re.compile(
    r'\b(?P<type>[A-Za-z_][A-Za-z0-9_]*(?:Error|Exception)):\s*(?P<message>.*)'
)
_PYTEST_EXCEPTION = re.compile(
    r'^\s*E\s+(?P<type>[A-Za-z_][A-Za-z0-9_]*(?:Error|Exception)):\s*(?P<message>.*)'
)


def _root_relative(raw_path: str, root: Path) -> str:
    """Return a root-confined relative path, or an empty string."""
    candidate = Path(raw_path)
    if not candidate.is_absolute():
        candidate = root / candidate
    try:
        resolved = candidate.resolve()
        if resolved == root or root not in resolved.parents:
            return ""
        return resolved.relative_to(root).as_posix()
    except (OSError, ValueError):
        return ""


def _is_test_path(path: str) -> bool:
    name = Path(path).name.lower()
    return (
        name.startswith(("test_", "test-", "tests."))
        or name.endswith(("_test.py", ".test.js", ".spec.js"))
        or "/tests/" in f"/{path}/"
    )


def extract_first_failure(result_content: str, project_root) -> PrimaryFailure | None:
    """Extract one first actionable failure without asking a model to interpret it.

    The parser supports common Python/pytest and JavaScript-style output.  It
    intentionally returns one failure, while the caller can retain the raw
    stream in telemetry for later diagnosis.
    """
    text = str(result_content or "")
    lines = text.splitlines()
    candidates: list[tuple[int, PrimaryFailure]] = []
    root = Path(project_root).resolve()

    for index, line in enumerate(lines):
        location = _TRACE_LOCATION.search(line) or _COMPACT_LOCATION.search(line)
        if location:
            raw_path = location.group("path")
            path = _root_relative(raw_path, root)
            try:
                line_number = int(location.group("line"))
            except (TypeError, ValueError):
                line_number = None
            error_type = ""
            message = ""
            for following in lines[index + 1:index + 8]:
                match = _EXCEPTION.search(following) or _PYTEST_EXCEPTION.search(following)
                if match:
                    error_type = match.group("type")
                    message = match.group("message").strip()[:500]
                    break
            if path or error_type:
                candidates.append((index, PrimaryFailure(
                    kind="traceback",
                    error_type=error_type,
                    message=message,
                    path=path,
                    line=line_number,
                )))

        test_match = _TEST_FAILURE.search(line)
        if test_match:
            candidates.append((index, PrimaryFailure(
                kind="test_failure",
                message=(test_match.group("message") or "").strip()[:500],
                test_id=test_match.group("test"),
            )))

        exception = _PYTEST_EXCEPTION.search(line) or _EXCEPTION.search(line)
        if exception:
            candidates.append((index, PrimaryFailure(
                kind="exception",
                error_type=exception.group("type"),
                message=exception.group("message").strip()[:500],
            )))

    if not candidates:
        lower = text.lower()
        setup_marker = next((marker for marker in (
            "no tests", "no test", "module not found", "modulenotfounderror",
            "npm err!", "could not start", "connection refused", "permission denied",
        ) if marker in lower), "")
        if setup_marker:
            return PrimaryFailure(kind="setup", message=setup_marker)
        return None

    candidates.sort(key=lambda item: item[0])
    return candidates[0][1]


def _command_from_args(arguments) -> str:
    raw = (arguments or {}).get("command", "")
    if isinstance(raw, (list, tuple)):
        return " ".join(str(part) for part in raw)
    return str(raw or "")


def _safe_cwd(arguments, root: Path) -> str:
    """Keep host-specific absolute directories out of model-facing packets."""
    raw = str((arguments or {}).get("cwd", ".") or ".")
    if not Path(raw).is_absolute():
        return raw[:MAX_CWD]
    relative = _root_relative(raw, root)
    return ("." if Path(raw).resolve() == root else relative or "<external>")[:MAX_CWD]


def _exit_code(result_content: str) -> int | None:
    match = re.search(r"\b(?:exit\s+code|returncode|status)\s*[:=]\s*(-?\d+)\b", str(result_content or ""), re.I)
    return int(match.group(1)) if match else None


def _classification(tool_name: str, result_content: str, failure: PrimaryFailure | None) -> str:
    lower = str(result_content or "").lower()
    if any(marker in lower for marker in (
        "no tests", "no test", "ran 0 tests", "module not found", "modulenotfounderror",
        "dependency", "npm err!", "could not start", "connection refused", "permission denied",
    )):
        return "setup_failure"
    if failure and failure.kind == "setup":
        return "setup_failure"
    if tool_name == "run_tests" or failure and failure.error_type:
        return "behavior_failure"
    if any(marker in lower for marker in ("assertionerror", "tests failed", "failed:")):
        return "behavior_failure"
    return "unknown_failure"


def build_failed_validation_packet(
    tool_name: str,
    arguments,
    result_content: str,
    project_root,
    changed_paths=(),
) -> FailedValidationPacket:
    """Build a bounded packet from host evidence only."""
    root = Path(project_root).resolve()
    failure = extract_first_failure(result_content, root)
    source: list[str] = []
    tests: list[str] = []
    if failure and failure.path:
        (tests if _is_test_path(failure.path) else source).append(failure.path)
    for raw in changed_paths:
        path = _root_relative(str(raw), root)
        if path and path not in source and path not in tests:
            # Changed paths are provenance, not failure evidence.  They are
            # kept only for overlap checks and never promoted to a failure.
            continue
    overlaps = tuple(path for path in source if path in {
        _root_relative(str(raw), root) for raw in changed_paths
    })
    evidence_parts = []
    if failure:
        evidence_parts.append(f"first={failure.kind}")
        if failure.error_type:
            evidence_parts.append(f"error={failure.error_type}")
        if failure.message:
            evidence_parts.append(f"message={failure.message[:500]}")
        if failure.path:
            evidence_parts.append(f"path={failure.path}")
        if failure.line is not None:
            evidence_parts.append(f"line={failure.line}")
        if failure.test_id:
            evidence_parts.append(f"test={failure.test_id[:MAX_TEST_ID]}")
    else:
        evidence_parts.append("first_failure=not_parsed")
    evidence = "; ".join(evidence_parts)[:MAX_EVIDENCE]
    digest = hashlib.sha256(evidence.encode("utf-8")).hexdigest()
    packet = FailedValidationPacket(
        schema_version=SCHEMA_VERSION,
        validation_status=_classification(tool_name, result_content, failure),
        tool_name=str(tool_name),
        executed_command=_command_from_args(arguments)[:MAX_COMMAND],
        cwd=_safe_cwd(arguments, root),
        exit_code=_exit_code(result_content),
        primary_failure=failure,
        detected_test_path=tests[0] if tests else (failure.test_id.split("::", 1)[0] if failure and failure.test_id else ""),
        detected_source_path=source[0] if source else "",
        transaction_overlaps=overlaps[:MAX_PATHS],
        source_paths=tuple(source[:MAX_PATHS]),
        test_paths=tuple(tests[:MAX_PATHS]),
        deterministic_evidence=evidence,
        evidence_sha256=digest,
    )
    return packet
